version: "3"
services:
  os:
    image: ubuntu:16.04
    volumes:
      - .:/home/
    command: >
      bash -c 
      "apt update --yes && 
      apt install --yes software-properties-common && 
      apt-add-repository --yes --update ppa:ansible/ansible && 
      apt install --yes ansible && 
      tail -f /dev/null"
